CREATE TABLE IF NOT EXISTS PRODUCTS 
(
PRODUCT_ID INT,
PRODUCT_NAME TEXT,
SUPPLIER_ID INT,
CUSTOMER_ID INT,
UNIT TEXT,
PRICE REAL
);

INSERT INTO PRODUCTS VALUES 
(1, 'CHAIS', 1, 1, '10 Boxes x 20 Bags', 18),
(2, 'CHANG', 1, 1, '12-24 oz Bottles', 19),
(3, 'ANISEED SYRUP', 1, 2, '30-550 ml Bottles', 10),
(4, 'CHEF ANTON SEASONING', 2, 2, '48-6 oz Jars', 22),
(5, 'CHEF ANTON MIX', 2, 2, '36 Boxes', 21.38);

SELECT COUNT(PRODUCT_ID) FROM PRODUCTS;

SELECT AVG(PRICE) FROM PRODUCTS;

SELECT SUM(PRICE) FROM PRODUCTS;

SELECT COUNT(PRODUCT_ID), AVG(PRICE), SUM(PRICE) FROM PRODUCTS;

SELECT COUNT(PRODUCT_ID) AS NO_OF_PRODUCTS FROM PRODUCTS;

SELECT AVG(PRICE) AS AVG_PRICE FROM PRODUCTS;

SELECT SUM(PRICE) AS SUM_OF_PRICE FROM PRODUCTS;

SELECT COUNT(PRODUCT_ID) AS NO_OF_PRODUCTS, AVG(PRICE) AS AVG_PRICE, SUM(PRICE) AS SUM_OF_PRICE FROM PRODUCTS;

SELECT MAX(PRICE) AS MAX_PRICE FROM PRODUCTS;
SELECT MIN(PRICE) AS MIN_PRICE FROM PRODUCTS;

SELECT * FROM PRODUCTS WHERE PRICE > 15;

SELECT COUNT(DISTINCT SUPPLIER_ID) AS UNIQUE_SUPPLIERS FROM PRODUCTS;