CREATE TABLE IF NOT EXISTS Employee 
(
ID INT,
NAME TEXT,
SALARY REAL
);

INSERT INTO Employee VALUES 
(1, 'John McCarty', 23),
(2, 'Lee Chon Wong', 35),
(3, 'Andrew Brace', 25),
(4, 'Tom Scott', 23),
(5, 'Jenny Opeck', 30);

SELECT COUNT(SALARY) AS TOTAL_SALARY FROM Employee;

SELECT AVG(SALARY) AS AVG_SALARY FROM Employee;

SELECT SUM(SALARY) AS SUM_OF_SALARY FROM Employee;

SELECT MAX(SALARY) AS MAX_SALARY FROM Employee;
SELECT MIN(SALARY) AS MIN_SALARY FROM Employee;
